services:
  client:
    build:
      context: .
    ports:
      - "3000:3000"
      - "3333:3333"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./:/opt/app
      - node_modules:/opt/app/node_modules

volumes:
  node_modules: {}
